/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments.index'
import { Route as TeamsIndexRouteImport } from './routes/teams.index'
import { Route as TeamsAddRouteImport } from './routes/teams.add'
import { Route as StadiumsAddRouteImport } from './routes/stadiums.add'
import { Route as TournamentsLeagueIdIndexRouteImport } from './routes/tournaments.$leagueId.index'
import { Route as TournamentsLeagueIdScheduleIndexRouteImport } from './routes/tournaments.$leagueId.schedule.index'
import { Route as TournamentsLeagueIdScheduleSelectRoundRouteImport } from './routes/tournaments.$leagueId.schedule.select-round'
import { Route as TournamentsLeagueIdScheduleAddMatchRouteImport } from './routes/tournaments.$leagueId.schedule.add-match'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsAddRoute = TeamsAddRouteImport.update({
  id: '/teams/add',
  path: '/teams/add',
  getParentRoute: () => rootRouteImport,
} as any)
const StadiumsAddRoute = StadiumsAddRouteImport.update({
  id: '/stadiums/add',
  path: '/stadiums/add',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsLeagueIdIndexRoute =
  TournamentsLeagueIdIndexRouteImport.update({
    id: '/tournaments/$leagueId/',
    path: '/tournaments/$leagueId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentsLeagueIdScheduleIndexRoute =
  TournamentsLeagueIdScheduleIndexRouteImport.update({
    id: '/tournaments/$leagueId/schedule/',
    path: '/tournaments/$leagueId/schedule/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentsLeagueIdScheduleSelectRoundRoute =
  TournamentsLeagueIdScheduleSelectRoundRouteImport.update({
    id: '/tournaments/$leagueId/schedule/select-round',
    path: '/tournaments/$leagueId/schedule/select-round',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentsLeagueIdScheduleAddMatchRoute =
  TournamentsLeagueIdScheduleAddMatchRouteImport.update({
    id: '/tournaments/$leagueId/schedule/add-match',
    path: '/tournaments/$leagueId/schedule/add-match',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stadiums/add': typeof StadiumsAddRoute
  '/teams/add': typeof TeamsAddRoute
  '/teams': typeof TeamsIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/tournaments/$leagueId': typeof TournamentsLeagueIdIndexRoute
  '/tournaments/$leagueId/schedule/add-match': typeof TournamentsLeagueIdScheduleAddMatchRoute
  '/tournaments/$leagueId/schedule/select-round': typeof TournamentsLeagueIdScheduleSelectRoundRoute
  '/tournaments/$leagueId/schedule': typeof TournamentsLeagueIdScheduleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stadiums/add': typeof StadiumsAddRoute
  '/teams/add': typeof TeamsAddRoute
  '/teams': typeof TeamsIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/tournaments/$leagueId': typeof TournamentsLeagueIdIndexRoute
  '/tournaments/$leagueId/schedule/add-match': typeof TournamentsLeagueIdScheduleAddMatchRoute
  '/tournaments/$leagueId/schedule/select-round': typeof TournamentsLeagueIdScheduleSelectRoundRoute
  '/tournaments/$leagueId/schedule': typeof TournamentsLeagueIdScheduleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stadiums/add': typeof StadiumsAddRoute
  '/teams/add': typeof TeamsAddRoute
  '/teams/': typeof TeamsIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/tournaments/$leagueId/': typeof TournamentsLeagueIdIndexRoute
  '/tournaments/$leagueId/schedule/add-match': typeof TournamentsLeagueIdScheduleAddMatchRoute
  '/tournaments/$leagueId/schedule/select-round': typeof TournamentsLeagueIdScheduleSelectRoundRoute
  '/tournaments/$leagueId/schedule/': typeof TournamentsLeagueIdScheduleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/stadiums/add'
    | '/teams/add'
    | '/teams'
    | '/tournaments'
    | '/tournaments/$leagueId'
    | '/tournaments/$leagueId/schedule/add-match'
    | '/tournaments/$leagueId/schedule/select-round'
    | '/tournaments/$leagueId/schedule'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/stadiums/add'
    | '/teams/add'
    | '/teams'
    | '/tournaments'
    | '/tournaments/$leagueId'
    | '/tournaments/$leagueId/schedule/add-match'
    | '/tournaments/$leagueId/schedule/select-round'
    | '/tournaments/$leagueId/schedule'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/stadiums/add'
    | '/teams/add'
    | '/teams/'
    | '/tournaments/'
    | '/tournaments/$leagueId/'
    | '/tournaments/$leagueId/schedule/add-match'
    | '/tournaments/$leagueId/schedule/select-round'
    | '/tournaments/$leagueId/schedule/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  StadiumsAddRoute: typeof StadiumsAddRoute
  TeamsAddRoute: typeof TeamsAddRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
  TournamentsLeagueIdIndexRoute: typeof TournamentsLeagueIdIndexRoute
  TournamentsLeagueIdScheduleAddMatchRoute: typeof TournamentsLeagueIdScheduleAddMatchRoute
  TournamentsLeagueIdScheduleSelectRoundRoute: typeof TournamentsLeagueIdScheduleSelectRoundRoute
  TournamentsLeagueIdScheduleIndexRoute: typeof TournamentsLeagueIdScheduleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/add': {
      id: '/teams/add'
      path: '/teams/add'
      fullPath: '/teams/add'
      preLoaderRoute: typeof TeamsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stadiums/add': {
      id: '/stadiums/add'
      path: '/stadiums/add'
      fullPath: '/stadiums/add'
      preLoaderRoute: typeof StadiumsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$leagueId/': {
      id: '/tournaments/$leagueId/'
      path: '/tournaments/$leagueId'
      fullPath: '/tournaments/$leagueId'
      preLoaderRoute: typeof TournamentsLeagueIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$leagueId/schedule/': {
      id: '/tournaments/$leagueId/schedule/'
      path: '/tournaments/$leagueId/schedule'
      fullPath: '/tournaments/$leagueId/schedule'
      preLoaderRoute: typeof TournamentsLeagueIdScheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$leagueId/schedule/select-round': {
      id: '/tournaments/$leagueId/schedule/select-round'
      path: '/tournaments/$leagueId/schedule/select-round'
      fullPath: '/tournaments/$leagueId/schedule/select-round'
      preLoaderRoute: typeof TournamentsLeagueIdScheduleSelectRoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$leagueId/schedule/add-match': {
      id: '/tournaments/$leagueId/schedule/add-match'
      path: '/tournaments/$leagueId/schedule/add-match'
      fullPath: '/tournaments/$leagueId/schedule/add-match'
      preLoaderRoute: typeof TournamentsLeagueIdScheduleAddMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  StadiumsAddRoute: StadiumsAddRoute,
  TeamsAddRoute: TeamsAddRoute,
  TeamsIndexRoute: TeamsIndexRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
  TournamentsLeagueIdIndexRoute: TournamentsLeagueIdIndexRoute,
  TournamentsLeagueIdScheduleAddMatchRoute:
    TournamentsLeagueIdScheduleAddMatchRoute,
  TournamentsLeagueIdScheduleSelectRoundRoute:
    TournamentsLeagueIdScheduleSelectRoundRoute,
  TournamentsLeagueIdScheduleIndexRoute: TournamentsLeagueIdScheduleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
